environment:
  matrix:
    - nodejs_version: '10'

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Install-Product node $env:nodejs_version

install:
  - npm install 

test_script:
  - npm test --color

# Don't actually build.
build: off